from pathlib import Path
import json

result = {
  "nodes": [
    {"id":"auth_gate_plan","label":"Auth Gate Implementation Plan v1 + v2","file_type":"document","source_file":"auth-gate-implementation-plan.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"claude_md","label":"CLAUDE.md Architecture Backbone","file_type":"document","source_file":"CLAUDE.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"manifest_yml","label":"figaf-manager CF Manifest","file_type":"document","source_file":"apps/figaf-manager/manifest.yml","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"cloud_index_html","label":"Cloud Renderer Shell index.html","file_type":"code","source_file":"apps/figaf-manager/cloud/index.html","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"setup_html","label":"Token Claim Page setup.html","file_type":"code","source_file":"apps/figaf-manager/cloud/setup.html","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"maintenance_html","label":"XSUAA Upgrade Maintenance Page","file_type":"code","source_file":"packages/manager-approuter/maintenance.html","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"ui_index_html","label":"Electron Renderer Shell packages/ui/index.html","file_type":"code","source_file":"packages/ui/index.html","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"v1_token_gate","label":"v1 Token Gate Cockpit-Log Token + Single-Use Claim","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"Part I","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"v2_xsuaa_upgrade","label":"v2 XSUAA Upgrade Persistent SAP IdP Auth via Bundled Approuter","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"Part II","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"cloud_auth_js","label":"cloud/auth.js Token Lifecycle + Cookie Signing","file_type":"code","source_file":"apps/figaf-manager/cloud/auth.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"cloud_server_js","label":"cloud/server.js Express + WebSocketServer","file_type":"code","source_file":"apps/figaf-manager/cloud/server.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"cloud_client_js","label":"cloud/client.js Browser window.figaf Shim","file_type":"code","source_file":"apps/figaf-manager/cloud/client.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"orchestrator_js","label":"packages/core/orchestrator.js IPC Handlers + HostAdapter","file_type":"code","source_file":"packages/core/orchestrator.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"app_jsx","label":"packages/ui/app.jsx Wizard State Machine","file_type":"code","source_file":"packages/ui/app.jsx","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"mode_js","label":"packages/ui/mode.js figafModeFlags Feature Flags","file_type":"code","source_file":"packages/ui/mode.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"screen_xsuaa_jsx","label":"screen-xsuaa.jsx XSUAA Upgrade UI Screens","file_type":"code","source_file":"packages/ui/screens/screen-xsuaa.jsx","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"manager_approuter_pkg","label":"packages/manager-approuter Wizard XSUAA Approuter Package","file_type":"code","source_file":"packages/manager-approuter/package.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"build_zip_js","label":"scripts/build-zip.js Cloud Zip Assembler","file_type":"code","source_file":"apps/figaf-manager/scripts/build-zip.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"idle_self_destruct","label":"Idle Self-Destruct FIGAF_IDLE_SELF_DESTRUCT_HOURS","file_type":"rationale","source_file":"apps/figaf-manager/manifest.yml","source_location":"env block","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"signed_session_cookie","label":"Signed Flag Cookie HMAC-SHA256 IP+UA Binding","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q2","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"ws_upgrade_auth","label":"WebSocket Auth at Upgrade Handler close code 4003/4004","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q4","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"redact_layer","label":"Layered Token Redaction upstream parse + downstream regex","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q6","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"two_app_approuter","label":"Two-App Approuter Architecture for v2 XSUAA","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"2.3","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"restage_self_handoff","label":"Restage-Self Handoff Sequence Phase 1/2/3","file_type":"rationale","source_file":"auth-gate-implementation-plan.md","source_location":"2.2","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"auth_kicked_flag","label":"figaf:auth-kicked sessionStorage Flag","file_type":"rationale","source_file":"apps/figaf-manager/cloud/index.html","source_location":"inline script","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"figaf_mode_inject","label":"FIGAF_MODE_INJECT Server-Side Mode Injection","file_type":"rationale","source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 20","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"host_adapter_seam","label":"HostAdapter Only Seam Between figaf-local and figaf-manager","file_type":"rationale","source_file":"CLAUDE.md","source_location":"Node C","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"window_figaf_ipc","label":"window.figaf IPC Surface prereq btp cf config shell","file_type":"rationale","source_file":"CLAUDE.md","source_location":"Top-level graph","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"manager_approuter_server_js","label":"packages/manager-approuter/server.js Approuter Wrapper + Health Endpoints","file_type":"code","source_file":"packages/manager-approuter/server.js","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"manager_xs_security_json","label":"packages/manager-approuter/xs-security.json Wizard XSUAA Descriptor","file_type":"code","source_file":"packages/manager-approuter/xs-security.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"deploy_templates_approuter","label":"packages/deploy-templates/approuter Figaf Tool Approuter Reference Shape","file_type":"code","source_file":"packages/deploy-templates/approuter/xs-app.json","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None}
  ],
  "edges": [
    {"source":"auth_gate_plan","target":"cloud_auth_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.4","weight":1.0},
    {"source":"auth_gate_plan","target":"setup_html","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.4","weight":1.0},
    {"source":"auth_gate_plan","target":"cloud_server_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.4","weight":1.0},
    {"source":"auth_gate_plan","target":"cloud_client_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.4","weight":1.0},
    {"source":"auth_gate_plan","target":"cloud_index_html","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.4","weight":1.0},
    {"source":"auth_gate_plan","target":"orchestrator_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.9","weight":1.0},
    {"source":"auth_gate_plan","target":"app_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.9","weight":1.0},
    {"source":"auth_gate_plan","target":"mode_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.9","weight":1.0},
    {"source":"auth_gate_plan","target":"build_zip_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.9","weight":1.0},
    {"source":"auth_gate_plan","target":"manager_approuter_pkg","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.4","weight":1.0},
    {"source":"auth_gate_plan","target":"maintenance_html","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.4","weight":1.0},
    {"source":"auth_gate_plan","target":"manager_xs_security_json","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.6","weight":1.0},
    {"source":"auth_gate_plan","target":"idle_self_destruct","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.10 V4","weight":1.0},
    {"source":"auth_gate_plan","target":"claude_md","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.1.1","weight":1.0},
    {"source":"v1_token_gate","target":"auth_gate_plan","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"0.1","weight":1.0},
    {"source":"v2_xsuaa_upgrade","target":"auth_gate_plan","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"0.1","weight":1.0},
    {"source":"signed_session_cookie","target":"cloud_auth_js","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q2","weight":1.0},
    {"source":"ws_upgrade_auth","target":"cloud_server_js","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q4","weight":1.0},
    {"source":"redact_layer","target":"cloud_server_js","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"1.2 Q6","weight":1.0},
    {"source":"two_app_approuter","target":"manager_approuter_pkg","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.3","weight":1.0},
    {"source":"restage_self_handoff","target":"maintenance_html","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.2","weight":1.0},
    {"source":"idle_self_destruct","target":"manifest_yml","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/manifest.yml","source_location":"env block","weight":1.0},
    {"source":"claude_md","target":"cloud_server_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"cloud_client_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"orchestrator_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"app_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"mode_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Node A","weight":1.0},
    {"source":"claude_md","target":"manifest_yml","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"build_zip_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"File map","weight":1.0},
    {"source":"claude_md","target":"ui_index_html","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Node A","weight":1.0},
    {"source":"claude_md","target":"cloud_index_html","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Node A","weight":1.0},
    {"source":"claude_md","target":"host_adapter_seam","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Node C","weight":1.0},
    {"source":"claude_md","target":"window_figaf_ipc","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Top-level graph","weight":1.0},
    {"source":"cloud_index_html","target":"cloud_client_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 45","weight":1.0},
    {"source":"cloud_index_html","target":"mode_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 23","weight":1.0},
    {"source":"cloud_index_html","target":"app_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 58","weight":1.0},
    {"source":"cloud_index_html","target":"screen_xsuaa_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 56","weight":1.0},
    {"source":"cloud_index_html","target":"auth_kicked_flag","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"inline script","weight":1.0},
    {"source":"cloud_index_html","target":"figaf_mode_inject","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/index.html","source_location":"line 20","weight":1.0},
    {"source":"ui_index_html","target":"mode_js","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"packages/ui/index.html","source_location":"line 19","weight":1.0},
    {"source":"ui_index_html","target":"app_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"packages/ui/index.html","source_location":"line 33","weight":1.0},
    {"source":"ui_index_html","target":"screen_xsuaa_jsx","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"packages/ui/index.html","source_location":"line 31","weight":1.0},
    {"source":"setup_html","target":"cloud_server_js","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/cloud/setup.html","source_location":"fetch /setup/claim","weight":1.0},
    {"source":"maintenance_html","target":"manager_approuter_server_js","relation":"calls","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"packages/manager-approuter/maintenance.html","source_location":"fetch /_manager-health","weight":1.0},
    {"source":"manager_approuter_pkg","target":"deploy_templates_approuter","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md","source_location":"2.3","weight":0.7},
    {"source":"manifest_yml","target":"auth_gate_plan","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"apps/figaf-manager/manifest.yml","source_location":"inline comment","weight":1.0},
    {"source":"setup_html","target":"maintenance_html","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.75,"source_file":"auth-gate-implementation-plan.md","source_location":None,"weight":0.75},
    {"source":"cloud_index_html","target":"ui_index_html","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"CLAUDE.md","source_location":"Node A","weight":0.85},
    {"source":"window_figaf_ipc","target":"cloud_client_js","relation":"implements","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Top-level graph","weight":1.0},
    {"source":"host_adapter_seam","target":"orchestrator_js","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"CLAUDE.md","source_location":"Node B","weight":1.0}
  ],
  "hyperedges": [
    {"id":"v1_auth_gate_composition","label":"v1 Auth Gate Token Generation + Single-Use Claim + Signed Cookie","nodes":["cloud_auth_js","setup_html","cloud_server_js"],"relation":"implement","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md"},
    {"id":"v2_xsuaa_upgrade_flow","label":"v2 XSUAA Upgrade Approuter Package + Maintenance Page + Manager Restage","nodes":["manager_approuter_pkg","maintenance_html","manager_approuter_server_js"],"relation":"implement","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"auth-gate-implementation-plan.md"},
    {"id":"dual_renderer_shell","label":"Dual Renderer Shell Both index.html Shells Load Same React Screens + mode.js","nodes":["cloud_index_html","ui_index_html","mode_js"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.85,"source_file":"CLAUDE.md"}
  ],
  "input_tokens": 9800,
  "output_tokens": 2100
}

out = Path("graphify-out/.graphify_chunk_01.json")
out.write_text(json.dumps(result), encoding="utf-8")
print("Written to", out.resolve())
